# Generated by Django 4.1.2 on 2023-08-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acountName', models.CharField(max_length=1000)),
                ('acountNumber', models.IntegerField(default=0, unique=True)),
                ('day', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('key', models.IntegerField(unique=True)),
            ],
        ),
    ]
