# Generated by Django 4.1.2 on 2023-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='time',
            name='startTime',
        ),
        migrations.AddField(
            model_name='time',
            name='timearray',
            field=models.CharField(default=['0,0,0,0,0,0,0'], max_length=1000),
        ),
        migrations.AlterField(
            model_name='time',
            name='acountNumber',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='key',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
